### ISSUE TITLE
[Bug]: Model attributes don't clear in between generation steps for comma-separated command parameters

### ISSUE THREAD

**Issue by patton-dev** [alibori/laravel-api-resource-generator#3]
### What happened?

The attributes array is never cleared, so the resources will slowly collect attributes of the previously read models

### How to reproduce the bug

 php artisan api-resource:generate Address,Admin,Supplier,User
        
                                                                                

### Package Version

0

### PHP Version

8.3

### Which operating systems does with happen with?

Windows

**Comment by alibori** [comment]
Hey @gregorypatton !

Thank you for reporting this bug. I'm happy to say that is now fixed 😃 

Regards
